### ISSUE TITLE
Emote size and background transparency

### ISSUE THREAD

**Issue by rambopfc** [rambopfc/Twemo-Addon#2]
Newly added emotes will NOT display at 28x28. 32x32 is the only way to make them display. They also do not remove the background color like the original ones, instead they appear inside a small black box.

**Comment by Sk83rX** [comment]
[Twemo.zip](https://github.com/rambopfc/Twemo-Addon/files/118653/Twemo.zip)

**Comment by rambopfc** [comment]
Thanks to the above poster, the black box issue has been figured out.
